---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: aakash1998gadekar/spe-mini
        tag: latest
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: aakash1998gadekar
        image: aakash1998gadekar/spe-mini 
        state: started
        tty: yes
        interactive: yes

